CREATE TABLE "submissions" (
	"id" serial PRIMARY KEY NOT NULL,
	"nama" text NOT NULL,
	"nik" text,
	"tanggal_lahir" text,
	"telepon" text NOT NULL,
	"status_perkawinan" text,
	"nama_pasangan" text,
	"dealer" text NOT NULL,
	"merk_kendaraan" text,
	"model_kendaraan" text,
	"tipe_kendaraan" text,
	"warna_kendaraan" text,
	"harga_kendaraan" integer,
	"asuransi" text,
	"down_payment" integer,
	"tenor" integer,
	"angsuran" integer,
	"status" integer DEFAULT 1 NOT NULL,
	"spk_url" text,
	"bukti_bayar_url" text,
	"ktp_url" text,
	"kk_url" text,
	"ttd_konsumen" text,
	"ttd_marketing" text,
	"ttd_dealer" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
